import {
    FaSnowflake,
    FaWater,
    FaWifi,
    FaLock,
    FaShower,
    FaBed,
    FaPhone,
    FaTv,
    FaHeadphones,
    FaEye,
    FaToiletPaper,
    FaFeatherAlt,
    FaNewspaper,
    FaPlug,
    FaChair,
    FaClock,
    FaBath,
    FaUtensils,
    FaConciergeBell,
    FaVideo,
    FaBookOpen,
    FaShoppingBasket,
    FaCocktail,
    FaDoorClosed,
    FaMountain,
    FaSwimmingPool,
    FaDumbbell,
    FaSpa,
    FaDice,
    FaUmbrellaBeach,
    FaBasketballBall,
    FaPumpSoap,
  } from "react-icons/fa"
  import {
    GiToothbrush,
    GiPillow,
    GiIceCube,
    GiTeapot,
    GiLiquidSoap,
    GiRazor,
    GiSpray,
    GiMirrorMirror,
    GiWaterTank,
    GiRollingSuitcase,
    GiVacuumCleaner,
    GiWashingMachine,
    GiPowerButton,
    GiCampingTent,
  } from "react-icons/gi"
  import { BsSunglasses, BsFillPenFill } from "react-icons/bs"
  import { TbIroningFilled } from "react-icons/tb"
  import { MdBalcony, MdCelebration } from "react-icons/md"
  import { IoIosFitness } from "react-icons/io"
  import { ImFire } from "react-icons/im"
  import { IoGolf } from "react-icons/io5"
  import { RiHandSanitizerFill } from "react-icons/ri"
  
  export const amenityIcons = {
    "Air Conditioning": FaSnowflake,
    "Mineral Water": FaWater,
    "Toiletries": FaPumpSoap,
    "Wifi": FaWifi,
    "Safe": FaLock,
    "Dental Kit": GiToothbrush,
    "Water Heater": FaShower,
    "Extra Bedding": FaBed,
    "Pillow": GiPillow,
    "Mini Fridge": GiIceCube,
    "Telephone": FaPhone,
    "TV": FaTv,
    "Sound Speakers": FaHeadphones,
    'Kettle': GiTeapot,
    "Blackout Curtains": FaEye,
    'Hairdryer': FaToiletPaper,
    "Shampoo/Conditioner": GiLiquidSoap,
    "Bathrobe and Slippers": FaFeatherAlt,
    "Noise Canceling Headphones": FaHeadphones,
    "Eye Mask": BsSunglasses,
    "Shaving Kit": GiRazor,
    "Room Freshener": GiSpray,
    "Daily Newspaper": FaNewspaper,
    "Universal Power Adapters": FaPlug,
    'Chair': FaChair,
    "Shaving Mirror": GiMirrorMirror,
    "Writing Pad and Pen": BsFillPenFill,
    "Hand Sanitizer": RiHandSanitizerFill,
    "Purified Drinking Water": GiWaterTank,
    "Iron/Ironing Board": TbIroningFilled,
    "Charging Points": FaClock,
    "Hot & Cold Water": FaShower,
    "Hypoallergenic Bedding": FaFeatherAlt,
    "Fan": FaSnowflake,
    "Western Toilet Seat": FaBed,
    "Luggage Storage": GiRollingSuitcase,
    'Bathtub': FaBath,
    "24 hour Housekeeping": GiVacuumCleaner,
    "In Room Dining": FaUtensils,
    "Room Service": FaConciergeBell,
    "Ironing Service": TbIroningFilled,
    'Balcony': MdBalcony,
    "Laundry Services": GiWashingMachine,
    "Private Entrance": FaDoorClosed,
    "In Room Entertainment System": FaVideo,
    "Reading Lamp": FaBookOpen,
    "Smart TV with Streaming Apps": FaTv,
    "Private Fitness Trainer": IoIosFitness,
    "Private Butler Service": FaConciergeBell,
    "Local Shopping Guide": FaShoppingBasket,
    "Signature Welcome Drink": FaCocktail,
    "Soundproof Doors": FaDoorClosed,
    "Anti Glare Windows": GiPowerButton,
    "Scenic View Balcony": FaMountain,
    "Swimming Pool": FaSwimmingPool,
    'Gym': FaDumbbell,
    'Spa': FaSpa,
    'Sauna': ImFire,
    'Bar': FaCocktail,
    "Night Club": MdCelebration,
    "Indoor Games Room": FaDice,
    "Outdoor Camping Space": GiCampingTent,
    "Private Beach Access": FaUmbrellaBeach,
    "Mini Golf Course": IoGolf,
    "Sports Court": FaBasketballBall,
  }
  
  